name: Generate Contribution Calendar

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Kirtan24

          output: dist/metrics-isocalendar.svg

          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          config_timezone: Asia/Calcutta
          config_display: large
          config_twemoji: yes
          config_octicon: yes
